site_name: Cloud Resume API Challenge

theme:
  name: material
  # Fonts

  font:
    text: Roboto
  
  features:
    - toc.follow
  # icons
  icon:
    logo: material/apple-icloud
    favicon: images/cloud-resume-api-favicon.png
    repo: fontawesome/brands/git-alt 
  
  palette:
    #- primary: indigo

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

# Repo details
repo_url: https://github.com/rishabkumar7/cloud-resume-api
repo_name: rishabkumar7/cloud-resume-api

# Plugins